version: '2'
volumes:
  dev-db-data:
    driver: local
services:
  api:
    build: ./api
    ports:
      - "80:8080"
    links:
      - db
    environment:
      DB: mysql+pymysql://root:root@db:3306/resource_manager
      DB_CONNECTION_RECYCLE: 3600
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
  db:
    image: postgres:11.3  # https://hub.docker.com/_/mysql
    ports:
      - "32000:3306"
    volumes:
      - dev-db-data:/var/lib/mysql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: geoip
