version: '2'
volumes:
  dev-db-data:
    driver: local
services:
  api:
    build: ./api
    ports:
      - "80:8080"
    links:
      - db
    environment:
      DB: mysql+pymysql://root:root@db:3306/resource_manager
      DB_CONNECTION_RECYCLE: 3600
    depends_on:
      - db
  db:
    image: mysql:8.0.15  # https://hub.docker.com/_/mysql
    ports:
      - "32000:3306"
    volumes:
      - dev-db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root