version: '2'
volumes:
  dev-db-data:
    driver: local
services:
  api:
    build: ./api
    ports:
      - "80:8080"
    links:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: geoip
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
  db:
    image: postgres:11.3
    ports:
      - "32000:3306"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: geoip
